apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: influxdb
  name: influxdb
spec:
  ports:
  - name: "8083"
    port: 8083
    protocol: TCP
    targetPort: 8083
  - name: "8086"
    port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    service: influxdb
status:
  loadBalancer: {}
