apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: load-balancer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: load-balancer
    spec:
      containers:
      - env:
        - name: EXPIRATION_EMAIL
          value: dummy@mail.com
        - name: STAGING
          value: "true"
        - name: VULCAIN_ENV
          value: demo
        - name: VULCAIN_SERVER
          value: vulcain-ui.default:8080
        - name: VULCAIN_TOKEN
          value: ab690d50-e85d-11e6-b767-8f41c48a4483
        image: vulcain/load-balancer:1.1.27
        name: load-balancer
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 29000
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        resources: {}
      restartPolicy: Always
