apiVersion: v1
kind: Service
metadata:
  labels:
    service: load-balancer-public
  name: load-balancer-public
spec:
  type: LoadBalancer
  ports:
  - name: "80"
    port: 80
    protocol: TCP
  - name: "443"
    port: 443
    protocol: TCP
  selector:
    service: load-balancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: load-balancer
  name: load-balancer
spec:
  type: NodePort
  ports:
  - port: 29000
    protocol: TCP
  selector:
    service: load-balancer